python/tanzhou/taks/Django_test/Django_test/urls.py
# -*- coding: utf-8 -*-

"""Django_test URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from hello import views, urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(urls, namespace='hello')),
    url(r"logout/$", views.Logout.as_view(), name="logout"),
    # url(r'^1[3|4|5|7|8]\d{9}/$', views.Phone.as_view()),    #正则
    # url(r'^([0-9]{1})/$', views.Oddoff.as_view()),      #单个非命名
    # url(r'^([0-9]{1})([0-9]{1})/([0-9]{1})$', views.Alloff.as_view(), name='dg'),      #多个非命名
    # url(r'^(?P<num>[a-z]{1})$', views.Oddon.as_view()),      #单个命名
    # url(r'^(?P<three>[a-z]{1})(?P<tow>[a-z]{1})/(?P<one>[a-z]{1})$', views.Allon.as_view(), name='mm'),      #多个命名
    # url(r'^(?P<k>)$', views.RedicectPage.as_view()),      #重定向
]

python/tanzhou/taks/Django_test/hello/urls.py
# -*- coding: utf-8 -*-

"""Django_test URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from hello import views

urlpatterns = [
    url(r'^1[3|4|5|7|8]\d{9}/$', views.Phone.as_view()),    #正则
    url(r'^([0-9]{1})/$', views.Oddoff.as_view()),      #单个非命名
    url(r'^([0-9]{1})([0-9]{1})/([0-9]{1})$', views.Alloff.as_view(), name='dg'),      #多个非命名
    url(r'^(?P<num>[a-z]{1})$', views.Oddon.as_view()),      #单个命名
    url(r'^(?P<three>[a-z]{1})(?P<tow>[a-z]{1})/(?P<one>[a-z]{1})$', views.Allon.as_view(), name='mm'),      #多个命名
    url(r'^(?P<k>)$', views.RedicectPage.as_view()),      #重定向
    url(r'^render/test_01$', views.render_test_01.as_view()),      #render跳转01
    url(r'^render/test_02$', views.render_test_02.as_view()),      #render跳转02
    url(r'^render/filter_test01$', views.filter_test_01.as_view()),      #render跳转filter_01
    url(r'^render/filter_test02$', views.filter_test_02.as_view()),      #render跳转filter_02
    url(r'^render/models_test_01$', views.ModelOper.as_view()),      #render跳转models_test_02
    url(r'^render/models_test_02$', views.School.as_view()),      #render跳转models_test_02
    url(r'^render/register$', views.Register.as_view(), name="register"),      #注册页
    url(r'^render/login$', views.Login.as_view(), name="login"),      #登录页
    url(r"^render/index/$", views.Index.as_view(), name="index"),   #主页
    url(r"^render/register_tkad_01/$", views.Register.as_view()),   #注册页视图
    url(r"^render/home/$", views.Home.as_view()),   #权限
]

python/tanzhou/taks/Django_test/hello/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(u"标题", max_length=50, null=False)                  # 定义一个标题
    content = models.TextField(u"内容", null=False)
    class Meta:
        db_table = "Article"
        managed = True
        ordering = ['-id']
        verbose_name = u"主题"
        verbose_name_plural = u"主题列表"

        permissions = (
            ("view_Article", u"查看书籍"),
            ("update_Article", u"修改书籍"),
            ("del_Article", u"删除书籍")
        )

class ClassNum(models.Model):  #班号
    num = models.CharField(u'班号', max_length=200)

class Class(models.Model):  #班级
    name = models.CharField(u'名称', max_length=200)
    num = models.OneToOneField(ClassNum)   #班号一对一
    crt_time = models.DateField(auto_now_add=True)
    up_time = models.DateField(auto_now=True)

class Teacher(models.Model):  #老师
    name = models.CharField(u'名称', max_length=200)
    age = models.CharField(u'年龄', max_length=200)
    gender = models.SmallIntegerField(u'性别')
    cls = models.ForeignKey(Class)  # 班级多对一

class Student(models.Model):  #学生
    name = models.CharField(u'名称', max_length=255)
    age = models.CharField(u'年龄', max_length=200)
    cls = models.ForeignKey(Class)  #班级多对一
    teacher = models.ManyToManyField(Teacher)   #老师多对多
    gender = models.SmallIntegerField(u'性别')

class User(models.Model):   #账号密码
    username = models.CharField(u"用户名", max_length=25)
    password = models.CharField(u"密码", max_length=50)

class User_01(models.Model):   #表单用户
    headshot = models.ImageField(u"头像", upload_to="upload/%Y/%m/%d", null=True)
    username = models.CharField(u"用户名", max_length=25)
    password = models.CharField(u"密码", max_length=50)
    password1 = models.CharField(u"重复密码", max_length=50)
    gender = models.CharField(u'性别', max_length=25)
    age = models.CharField(u'出生年月', max_length=25)

python/tanzhou/taks/Django_test/templates/render/base_01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>base_01</div>
    {% block content %}
        <p>这是个默认的登录页</p>
    {% endblock content %}
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/filter_test01.html
{% extends 'render/base_01.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% load test_01 %}
    {% block content %}
        {{ name|mycut:' ' }}
        {% curr_date %}
        {% show_results %}
    {% endblock content %}
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/filter_test02.html
{% load test_01 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static '/css/test_01.css' %}">
</head>
<body>
{% show_results %}
<p>战锤小胖</p>
<img src="{% static '/img/L7F11M92OX@9NE2MN860{RE.png' %}" alt="">

<script src="{% static '/js/test_01.js' %}"></script>
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/include_01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {# 单行注释 #}
    {% comment %}多行注释{% endcomment %}
    <p>我是include_01的模板</p>
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

python/tanzhou/taks/Django_test/templates/render/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ ip }}
<form action="" method="post">
    {% csrf_token %}
    用户名: <input type="text" name="username" />
    密码: <input type="password" name="password" />
    <input type="submit" value="登录">
    <a href="render/logout/">注销</a>
</form>
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/models_test01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for articlea in articles %}
        <h1>{{ articlea.id }}.{{ articlea.title }}</h1>
        <p>{{ articlea.content }}</p>
        <hr>
    {% endfor %}

</body>
</html>

python/tanzhou/taks/Django_test/templates/render/models_test02.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        班号
        {% for val in classNums %}
            <li>{{ val.num }}</li>
        {% endfor %}
    </ul>
    <hr>
    <ul>
        班级
        {% for val in clss %}
            <li>
                名称：{{ val.name }} 班号：{{ val.num.num }} 创建日期：{{ val.crt_time|date:"Y-m-d" }} 更新日期：{{ val.up_time|date:"Y-m-d" }}
                老师:{% for tc in val.teacher_set.all %}{{ tc.name }} {% endfor %}
                学生:{% for st in val.student_set.all %}{{ st.name }} {% endfor %}
            </li>
        {% endfor %}
    </ul>
    <hr>
    <ul>
        老师
        {% for val in teachers %}
            <li>姓名：{{ val.name }} 年龄：{{ val.age }} 性别：{{ val.gender }} 班级：{{ val.cls.name }}</li>
        {% endfor %}
    </ul>
    <hr>
    <ul>
        学生
        {% for val in students %}
            <li>姓名：{{ val.name }} 年龄：{{ val.age }} 性别：{{ val.gender }} 班级：{{ val.cls.name }}
                老师：{% for tc in val.teacher.all %}{{ tc.name }} {% endfor %}
            </li>
        {% endfor %}
        <li>年龄最大的学生：{{ st_age_max.age }}</li>
        <li>年龄最小的学生：{{ st_age_min.age }}</li>
        <li>学生平均年龄：{{ st_age_avg.avg }}</li>
        <ul>人数分布：
            {% for nums in st_age_count %}
                <li>{{ nums.age }}岁 => {{ nums.num }}人</li>
            {% endfor %}

        </ul>
    </ul>
    <hr>
    <ul>
        性别为男的学生
        {% for val in gender_m %}
            <li>{{ val.name }}</li>
        {% endfor %}
    </ul>
    <hr>
    <ul>
        年龄大于20的学生
        {% for val in age_20up %}
            <li>{{ val.name }}</li>
        {% endfor %}
    </ul>
    <hr>
    <ul>
        学生年龄排序
        {% for val in age_order %}
            <li>{{ val.name }}：{{ val.age }}</li>
        {% endfor %}
    </ul>
    <hr>
        <ul>
        除了女学生
        {% for val in wm_except %}
            <li>{{ val.name }}</li>
        {% endfor %}
    </ul>
    <hr>
    <ul>
        学生总数：{{ std_all }}
    </ul>
    <hr>
    <ul>
        最后创建的班级：{{ cls_last.name }}
    </ul>
    <hr>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
    {% csrf_token %}
    <input type="text" name="username"/>
    <input type="password" name="password"/>
    <input type="submit" values="注册"/>
</form>
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/register_tkad_01.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ form.errors }}
<p>用户注册</p>
{# 如果表单需要上传文件，需要设置enctype="multipart/form-data" 否则文件无法找到 #}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
{#    头像上传： <input type="file" name="headshot"><br/>#}
    用户名： <input type="text" name="username"/> <br/>
    密码： <input type="password" name="password"/><br/>
{#    重复密码： <input type="password" name="password1"/><br/>#}
{#    性别：#}
{#    <select name="gender" id="">#}
{#        <option value="男">男</option>#}
{#        <option value="女">女</option>#}
{#    </select> <br/>#}
{#    生日： <input type="text" name="age"/> <br/>#}
    <input type="submit" values="注册"/>
</form>
</body>
</html>

python/tanzhou/taks/Django_test/templates/render/test_01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>我是测试页面01</div>
    {% for i, key in data_01.items %}
        {% if key == 'huren' %}
            <p>我是{{ key }}</p>
        {% elif key == 18%}
            <p>年龄{{ key }}</p>
        {% elif key == 'python' %}
            {{ key }}
        {%else%}
            <p>没这条数据</p>
        {% endif %}
    {% endfor %}

    {% for i, key in data_02.items %}
        {% if key == 'javascript' %}
            <p>小写转大写：{{ key|upper }}</p>
        {% elif key == 'JAVASCRIPT' %}
            <p>大写转小写：{{ key|lower }}</p>
        {% elif i == 'val_03' %}
            <p>时间转换：{{ key|date:"Y-m-d H:i:s" }}</p>
        {% elif key == 'Python WEB' %}
            <p>字符串处理：{{ key|cut:" " }}</p>
        {%else%}
            <p>没这条数据</p>
        {% endif %}
    {% endfor %}

</body>
</html>

python/tanzhou/taks/Django_test/templates/render/test_02.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'render/base_01.html' %}
    {% block content %}
        {% include 'render/include_01.html' %}
        <p>这是登陆注册页</p>
    {% endblock content %}
</body>
</html>